name: Deploy

on:
  workflow_run:
    workflows: [Build Docker Image]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      QUALIFIER: "analytics"
      AUTH_CLIENT_NAME: ${{ secrets.AUTH_CLIENT_NAME }}
      AUTH_CLIENT_SECRET: ${{ secrets.AUTH_CLIENT_SECRET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    container:
      image: 'ghcr.io/nasa-impact/veda-features-api:latest'
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Run
        shell: bash
        run: |
          cd /opt
          ./entrypoint.sh
